//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Quero_DE.rc
//
#define IDS_PROJNAME                    100
#define IDR_QUEROBAND                   101
#define IDM_QUERO                       102
#define IDM_LOGO                        103
#define IDC_COMBOENGINE                 104
#define IDC_EDITBOX                     105
#define IDC_COMBOQUERO                  106
#define IDS_QUEROFILTER_DESC            108
#define IDR_QUEROFILTER                 109
#define IDS_PROMPT                      110
#define IDS_EMPTY                       111
#define IDS_POPUPBLOCKED                112
#define IDS_CONTENTBLOCKED              113
#define IDS_HIGHLIGHTING                114
#define IDS_ON                          115
#define IDS_OFF                         116
#define IDS_LUCKYSEARCH                 117
#define IDS_FIND_FINISHED               118
#define IDS_FIND_NOTFOUND               119
#define IDS_CTXMENU_HIGHLIGHT           120
#define IDM_BACK                        120
#define IDS_CTXMENU_GOTOURL             121
#define IDM_FORWARD                     121
#define IDS_BLOCKED_MENU_1DIV           122
#define IDM_REFRESH                     122
#define IDS_BLOCKED_MENU_NDIVS          123
#define IDM_STOP                        123
#define IDS_BLOCKED_MENU_1ADSCRIPT      124
#define IDM_HOME                        124
#define IDS_BLOCKED_MENU_NADSCRIPTS     125
#define IDS_BLOCKED_MENU_BLOCK_ADS      126
#define IDS_BLOCKED_MENU_BLOCK_POPUPS   127
#define IDS_BLOCKED_MENU_ALLOWED_SITES  128
#define IDS_HISTORY                     129
#define IDS_PASTE_AND_GO                130
#define IDS_BLOCKED_MENU_TEMP_UNBLOCK   131
#define IDS_UP_ONE_LEVEL                132
#define IDI_QUERO                       140
#define IDI_QUERO_WHITE                 141
#define IDS_HINT_FIND                   150
#define IDS_HINT_QUERO_ALT_Q            151
#define IDS_HINT_QUERO_ALT_SHIFT_Q      152
#define IDS_HINT_GOTOURL                153
#define IDS_HINT_GOTOENGINE             154
#define IDS_HINT_QUERY                  155
#define IDS_HINT_BACK                   156
#define IDS_HINT_BACK_TO                157
#define IDS_HINT_FORWARD                158
#define IDS_HINT_FORWARD_TO             159
#define IDS_HINT_REFRESH                160
#define IDS_HINT_STOP                   161
#define IDS_HINT_HOME                   162
#define IDS_HINT_IDN                    163
#define IDS_HINT_123                    164
#define IDS_HINT_LOCK                   165
#define IDS_HINT_CONTENTBLOCKED         166
#define IDS_BLOCKED_MENU_HIDE_FLASH     167
#define IDS_HELP_FINDONPAGE             200
#define IDS_HELP_SELECTPROFILE          201
#define IDS_HELP_SELECTDEFAULT          202
#define IDI_BUTTON_GO                   202
#define IDC_CHKSHOWURL                  202
#define IDS_HELP_APPEARANCE             203
#define IDC_CHKIDNSUPPORT               203
#define IDS_HELP_RESIZE                 204
#define IDC_CHKHIGHLIGHT                204
#define IDS_HELP_HIGHLIGHT              205
#define IDI_BUTTON_GO_HOT               205
#define IDC_CHKBLOCKPOPUPS              205
#define IDC_SAVE_ADDRESS_HISTORY        205
#define IDS_HELP_BLOCKADS               206
#define IDC_CHKBLOCKFLASH               206
#define IDC_SHOW_SEARCH_TERMS_WHILE_SEARCHING 206
#define IDS_HELP_HIDEFLASHADS           207
#define IDR_MENU                        207
#define IDC_CHKGOBUTTON                 207
#define IDC_PAGE_LOADING_ANIMATION      207
#define IDS_HELP_BLOCKPOPUPS            208
#define IDC_CBOFONTSIZE                 208
#define IDC_HIGHLIGHT_IN_DIFFERENT_COLORS 208
#define IDS_HELP_CLEARHISTORY           209
#define IDC_CBOFONTCOLOR                209
#define IDC_ADDRESS_NAVIGATION          209
#define IDS_HELP_ABOUT                  210
#define IDC_CHKIDNWARNING               210
#define IDC_CHKBACKBUTTON               210
#define IDS_HELP_ZOOM                   211
#define IDC_TITLE                       211
#define IDC_CHKMISSGLYPHSWARNING        211
#define IDC_CHKFORWARDBUTTON            211
#define IDS_HELP_OPTIONS                212
#define IDC_DESCRIPTION                 212
#define IDC_CHKHIGHLIGHTDOMAIN          212
#define IDC_CHKREFRESHBUTTON            212
#define IDC_CHKADDTOWHITELIST           213
#define IDC_CHKDIGITASCIIINDICATOR      213
#define IDC_CHKSTOPBUTTON               213
#define IDC_CMDRESETWL                  214
#define IDC_CHKASCIIRULESWARNING        214
#define IDC_CHKHOMEBUTTON               214
#define IDI_SEARCH                      215
#define IDC_CHKSEARCHCOUNTRY            215
#define IDC_QUEROBUTTON                 215
#define ID_DISPLAY_CERTIFICATE_INFORMATION 215
#define IDI_URL                         216
#define IDC_SAVE_SEARCH_HISTORY         216
#define IDC_REMEMBER_LAST_SEARCH        217
#define IDC_CHKSHOWFIRSTURL             219
#define IDC_DISPLAY_PROMPT              219
#define IDC_CHKSEARCHONDNSFAILURE       221
#define IDI_ENGINE1                     222
#define IDC_CHKNAVIGATEONACSEL          222
#define IDI_BOOK                        223
#define IDC_CHKNAVIGATEONHISTSEL        223
#define IDI_CHART                       224
#define IDC_CHKACUSETAB                 224
#define IDI_MAP                         225
#define IDC_QUERO_CONTEXT_MENU_EXTENSION 225
#define IDI_MOVIE                       226
#define IDC_DPI_SCALING                 226
#define IDI_PRICE                       227
#define IDC_CMDRESTORE                  227
#define IDI_TELEPHONE                   228
#define IDC_CHKSHOWFAVICONSINTASKBAR    228
#define IDI_TRAIN                       229
#define IDC_CHKDOWNLOADFAVICON          229
#define IDI_TROLLEY                     230
#define IDC_RDOPOPUPBLOCKER_BLOCKUNWANTED 230
#define IDI_TV                          231
#define IDC_RDOPOPUPBLOCKER_BLOCKALL    231
#define IDI_WEATHER                     232
#define IDC_CHKPOPUPBLOCKER_PLAYSOUND   232
#define IDC_DOMAIN                      233
#define IDC_BLOCK_FLASH                 233
#define IDI_SCIENCE                     234
#define IDC_WHITELIST                   234
#define IDC_BLOCK_BANNER                234
#define IDC_ADD                         235
#define IDC_BLOCK_ADSCRIPT              235
#define IDD_OPTIONS_SETTINGS            236
#define IDC_DELETE                      236
#define IDC_ALLOW_IDN                   237
#define IDC_BLOCK_DIV                   237
#define IDI_IDN                         238
#define IDC_ALLOW_MISSGLYPHS            238
#define IDC_BLOCK_IFRAME                238
#define IDC_ALLOW_POPUPS                239
#define IDC_ALLOW_FLASH                 240
#define IDD_WARNING                     241
#define IDC_ALLOW_BANNER                241
#define IDB_SHIELD                      242
#define IDC_ALLOW_ADSCRIPT              242
#define IDC_ALLOW_DIV                   243
#define IDD_OPTIONS_ADVANCED            244
#define IDI_OPT_NAVIGATION              245
#define IDD_OPTIONS_SECURITY            245
#define IDC_CMDWHITELIST                245
#define IDC_ALLOW_IFRAME                245
#define IDC_SHOWSEARCHENGINECBOX        247
#define IDI_OPT_ADBLOCKER               248
#define IDC_BLOCK_ADS                   248
#define IDC_SHOWSEARCHBOX               248
#define IDI_OPT_SEARCH                  249
#define IDC_BLOCK_POPUPS                249
#define IDC_ENABLEAEROTHEME             249
#define IDS_OPTIONS_TITLE               250
#define IDC_DISABLE_AD_BLOCKER_FOR_LOCAL_WEB_SITES 250
#define IDC_IE_NAVIGATION_BAR           250
#define IDS_OPTION_STANDARD             251
#define IDC_IE_ADDRESS_BOX              251
#define IDC_HIDE_FLASH                  251
#define IDS_OPTION_MEDIUM               252
#define IDI_123                         252
#define IDC_DISABLE_AD_BLOCKER_FOR_HTTPS_WEB_SITES 252
#define IDC_FAVORITES_BUTTON            252
#define IDS_OPTION_LARGE                253
#define IDI_COMPASS                     253
#define IDC_TOOLBAR_CLOSE_BUTTON        253
#define IDS_OPTION_GREENBLUE            254
#define IDI_LOCK                        254
#define IDC_QUEROSHORTCUTKEY            254
#define IDC_IE_SHOW_CAPTION             254
#define IDS_OPTION_BLACK                255
#define IDI_OPT_SECURITY                255
#define IDC_CURRENT_USER_AGENT          255
#define IDC_IE_CAPTION_WHITE_TEXT       255
#define IDS_OPTION_CTRL_Q               256
#define IDC_UA_PLATFORM                 256
#define IDC_WHITE_QUERO_BUTTON          256
#define IDS_OPTION_ALT_Q                257
#define IDC_UA_PREFIX                   257
#define IDS_OPTION_ALT_D                258
#define IDC_UA_VERSION                  258
#define IDS_OPTION_ALT_S                259
#define IDI_NAV_BACK                    259
#define IDC_NEWWINTAB_SEARCHBOX         259
#define IDS_OPTION_OPEN_SAMEWINDOW      260
#define IDI_NAV_FORWARD                 260
#define IDC_UA_COMPATIBLE               260
#define IDS_OPTION_OPEN_NEWWINDOW       261
#define IDI_NAV_STOP                    261
#define IDC_NEWWINTAB_CONTEXTMENU       261
#define IDS_OPTION_OPEN_NEWTAB          262
#define IDI_NAV_REFRESH                 262
#define IDS_OPTION_OPEN_BACKGROUNDTAB   263
#define IDI_BIN                         263
#define IDS_PROFILES_DEFAULT            264
#define IDS_EDIT_SEARCH_PROFILE         265
#define IDD_WHITELIST                   265
#define IDC_QUEROTHEME_FILENAME         265
#define IDS_EDIT_SEARCH_ENGINE          266
#define IDD_OPTIONS_APPEARANCE          266
#define IDC_QUEROTHEME_BROWSE           266
#define IDS_CODEPAGE_UTF8               267
#define IDC_ICON_OPT_NAVIGATION         267
#define IDS_CODEPAGE_Arabic             268
#define IDC_ICON_OPT_SEARCH             268
#define IDS_CODEPAGE_Baltic             269
#define IDC_ICON_OPT_ADBLOCKER          269
#define IDD_OPTIONS_ADBLOCKER           269
#define IDS_CODEPAGE_Central_European   270
#define IDI_NAV_BACK_DISABLED           270
#define IDC_ICON_OPT_SECURITY           270
#define IDS_CODEPAGE_Chinese_Simplified_GB2312 271
#define IDI_NAV_FORWARD_DISABLED        271
#define IDC_BITMAP_SHIELD               271
#define IDS_CODEPAGE_Chinese_Traditional_BIG5 272
#define IDI_SEARCH_NOTFOUND             272
#define IDC_ICON_OPT_BUTTONS            272
#define IDS_CODEPAGE_Cyrillic           273
#define IDI_OPT_BUTTONS                 273
#define IDS_CODEPAGE_Greek              274
#define IDC_RESET                       274
#define IDI_NAV_BACK_HOT                274
#define IDS_CODEPAGE_Hebrew             275
#define IDI_NAV_FORWARD_HOT             275
#define IDC_QUICK_TYPE                  275
#define IDS_CODEPAGE_Japanese           276
#define IDI_NAV_REFRESH_HOT             276
#define IDC_QUICK_FIND                  276
#define IDS_CODEPAGE_Korean             277
#define IDI_NAV_STOP_HOT                277
#define IDS_CODEPAGE_Thai               278
#define IDI_OPT_TYPEFIND                278
#define IDS_CODEPAGE_Turkish            279
#define IDI_NAV_HOME                    279
#define IDS_CODEPAGE_Vietnamese         280
#define IDI_NAV_HOME_HOT                280
#define IDS_CODEPAGE_Western_European   281
#define IDS_OPTION_PINK                 282
#define IDD_ZOOMFACTOR                  283
#define IDC_SELECT_ALL                  284
#define IDC_ICON_OPT_TYPEFIND           285
#define IDD_RESIZEWINDOW                285
#define IDD_OPTIONS_PROFILES            287
#define IDD_SEARCHPROFILE               288
#define IDD_SEARCHENGINE                289
#define IDC_EDIT_ZOOMFACTOR             290
#define IDC_SPIN_ZOOMFACTOR             291
#define IDC_EDIT_WIDTH                  292
#define IDC_EDIT_HEIGHT                 293
#define IDC_PROFILES_NEW                294
#define IDC_PROFILES_DELETE             295
#define IDC_PROFILES_EDIT               296
#define IDC_PROFILES_MOVE_UP            297
#define IDC_PROFILES_MOVE_DOWN          298
#define IDC_PROFILES_RENAME             299
#define IDS_WL_ALLOW                    300
#define IDS_WL_DEFAULT                  301
#define IDC_PROFILES_LIST               301
#define IDS_WL_SITE                     302
#define IDC_PROFILES_INSERT_SEPARATOR   302
#define IDS_WL_FLASH                    303
#define IDC_ENGINES_LIST                303
#define IDS_WL_BANNER                   304
#define IDC_PROFILES_SET_DEFAULT        304
#define IDS_WL_ADSCRIPT                 305
#define IDC_PROFILES_RESET              305
#define IDS_WL_DIV                      307
#define IDC_PROFILE_NAME                307
#define IDS_WL_IFRAME                   308
#define IDC_PROFILE_LUCKYSEARCH         308
#define IDS_WL_POPUPS                   309
#define IDC_ENGINE_NAME                 309
#define IDS_WL_IDN                      310
#define IDC_ENGINE_QUERYURL             310
#define IDS_WL_GLYPHS                   311
#define IDC_ENGINE_POSTQUERY            311
#define IDS_WL_CONFIRM_RESET            312
#define IDC_ENGINE_LINKURL              312
#define IDC_ENGINE_COUNTRYPARAM         313
#define IDC_ENGINE_ICON                 314
#define IDC_ENGINE_ENCODING             315
#define IDC_STATIC_FRAME                319
#define IDC_ENGINE_ICON_BROWSE          320
#define IDC_STATIC_AD_BLOCKER_NOTE      320
#define IDC_QUERO_VERSION               321
#define IDS_WARN_IDN_TITLE              350
#define IDS_WARN_IDN_DESC               351
#define IDS_WARN_ILLEGAL_URL_TITLE      352
#define IDS_WARN_ILLEGAL_URL_DESC       353
#define IDS_WARN_MISSGLYPHS_TITLE       354
#define IDS_WARN_MISSGLYPHS_DESC        355
#define IDS_WARN_ASCIIRULES_VIOLATION_TITLE 356
#define IDS_WARN_ASCIIRULES_VIOLATION_DESC 357
#define IDS_ERR_QUERYTOOLONG            400
#define IDS_ERR_PUBLOCKER_UNAVAILABLE   401
#define IDS_ERR_WL_OVERFLOW             402
#define IDS_ERR_WL_PATTERNINVALID       403
#define IDS_ERR_WL_PATTERNNOTFOUND      404
#define IDS_ERR_PROFILES_OVERFLOW       405
#define IDS_ERR_SE_OVERFLOW             406
#define IDS_ERR_REQUIRED_FIELDS         407
#define IDS_ERR_OPERATION_LOCKED        408
#define IDS_TIP_QUERO_SHORTCUT          500
#define IDS_QUEROTHEME_FORMAT           1000
#define IDS_QUEROTHEME_VERSION          1001
#define IDS_QUEROTHEME_AUTHOR           1002
#define IDS_QUEROTHEME_NAME             1003
#define IDS_QUEROTHEME_NAVBUTTONSIZE    1004
#define IDS_QUEROTHEME_BUTTONSIZE       1005
#define IDS_QUEROTHEME_PADDINGY         1006
#define IDS_QUEROTHEME_COLORS           1100
#define ID_QUERO_WINDOWSIZE_640X480     30000
#define ID_QUERO_WINDOWSIZE_800X600     30001
#define ID_QUERO_WINDOWSIZE_880X660     30002
#define ID_QUERO_WINDOWSIZE_880X720     30003
#define ID_QUERO_WINDOWSIZE_880X960     30004
#define ID_QUERO_WINDOWSIZE_1024X768    30005
#define ID_QUERO_WINDOWSIZE_FULLSCREEN  30006
#define ID_QUERO_DEFAULTENGINE          31000
#define ID_QUERO_FINDWORD               32000
#define ID_QUERO_ABOUT                  32770
#define ID_QUERO_CLEARHISTORY           32772
#define ID_QUERO_SHOWURL                32774
#define ID_QUERO_FINDONPAGE_EMPTY       32775
#define ID_QUERO_FINDNEXT               32776
#define ID_QUERO_HIGHLIGHT              32778
#define ID_QUERO_BLOCKPOPUPS            32779
#define ID_QUERO_FONTSIZE_STANDARD      32781
#define ID_QUERO_FONTSIZE_MEDIUM        32782
#define ID_QUERO_FONTSIZE_LARGE         32783
#define ID_QUERO_DEFAULTENGINE_EMPTY    32784
#define ID_QUERO_BLOCKADS               32793
#define ID_QUERO_HIDEFLASHADS           32794
#define ID_QUERO_FONTCOLOR_GREENBLUE    32799
#define ID_QUERO_FONTCOLOR_BLACK        32800
#define ID_QUERO_ZOOM_50                32801
#define ID_QUERO_ZOOM_80                32802
#define ID_QUERO_ZOOM_100               32803
#define ID_QUERO_ZOOM_120               32804
#define ID_QUERO_ZOOM_150               32805
#define ID_QUERO_ZOOM_200               32806
#define ID_QUERO_ZOOM_400               32808
#define ID_QUERO_OPTIONS                32809
#define ID_QUERO_ZOOM_90                32812
#define ID_QUERO_ZOOM_110               32813
#define ID_QUERO_CSS_ZOOM               32818
#define ID_QUERO_OPTICAL_ZOOM           32819
#define ID_QUERO_CUSTOM_ZOOM            32820
#define ID_QUERO_RESIZEWINDOW_CUSTOM    32821
#define ID_QUERO_PROFILES_EMPTY         32823
#define ID_QUERO_RESIZEWINDOW_AUTO_MAXIMIZE 32824
#define ID_QUERO_PROFILES               33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        286
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         322
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
